/**
 * Nearby Homestays, Hotels, Restaurants, Locations, Prices, Signature Foods & Booking Links
 * Curated for India Heritage Explorer
 */

export interface NearbyHomestay {
  name: string;
  location: string;
  distanceFromSite: string;
  pricePerNight: string;
  priceNumeric: number;
  rating: number;
  hostExperience: string;
  amenities: string[];
  link: string;
}

export interface NearbyHotel {
  name: string;
  category: 'Heritage Palace' | 'Luxury Resort' | 'Boutique Hotel' | 'Comfort Hotel';
  location: string;
  distanceFromSite: string;
  pricePerNight: string;
  priceNumeric: number;
  rating: number;
  description: string;
  amenities: string[];
  link: string;
}

export interface NearbyRestaurant {
  name: string;
  cuisine: string;
  location: string;
  distanceFromSite: string;
  priceForTwo: string;
  rating: number;
  signatureFoods: string[];
  description: string;
  link: string;
}

export interface SiteTravelGuide {
  siteId: string;
  siteName: string;
  city: string;
  state: string;
  localFoodCulture: string;
  homestays: NearbyHomestay[];
  hotels: NearbyHotel[];
  restaurants: NearbyRestaurant[];
}

export const NEARBY_STAYS_FOOD_DATABASE: Record<string, SiteTravelGuide> = {
  'hawa-mahal': {
    siteId: 'hawa-mahal',
    siteName: 'Hawa Mahal',
    city: 'Jaipur',
    state: 'Rajasthan',
    localFoodCulture: 'Famed for royal Kachhwaha Rajput banquets, spicy pyaaz kachoris, ghewar soaked in saffron syrup, and dal baati churma baked over cow-dung cakes.',
    homestays: [
      {
        name: 'Dera Rawatsar Heritage Homestay',
        location: 'Bani Park, Jaipur',
        distanceFromSite: '3.8 km from Hawa Mahal',
        pricePerNight: '₹3,200 / night',
        priceNumeric: 3200,
        rating: 4.8,
        hostExperience: 'Family-run Rajput home with lush courtyard, traditional puppet shows, and authentic home-cooked Rajasthani thalis prepared by royal family recipes.',
        amenities: ['Courtyard Garden', 'Homemade Breakfast', 'AC Deluxe Rooms', 'Free Wi-Fi', 'Airport Shuttle'],
        link: 'https://www.booking.com/hotel/in/dera-rawatsar.html',
      },
      {
        name: 'Umaid Bhawan Heritage Home',
        location: 'Behari Marg, Bani Park, Jaipur',
        distanceFromSite: '4.2 km from Hawa Mahal',
        pricePerNight: '₹2,800 / night',
        priceNumeric: 2800,
        rating: 4.6,
        hostExperience: 'Showcases intricate fresco wall murals, carved balconies (jharokhas), and rooftop folk dance recitals under starlit skies.',
        amenities: ['Swimming Pool', 'Frescoed Lounge', 'Rooftop Restaurant', 'Cultural Evenings', 'Heritage Decor'],
        link: 'https://www.umaidbhawan.com/',
      },
      {
        name: 'Khatu Haveli Homestay',
        location: 'Old City, Badi Chaupar, Jaipur',
        distanceFromSite: '650 meters from Hawa Mahal',
        pricePerNight: '₹2,400 / night',
        priceNumeric: 2400,
        rating: 4.7,
        hostExperience: 'A 19th-century noble haveli tucked inside the walled pink city. Walk to Hawa Mahal in 7 minutes.',
        amenities: ['Historic Courtyard', 'Terrace Monument Views', 'Home Kitchen', 'Walking Tour Guides'],
        link: 'https://maps.google.com/?q=Khatu+Haveli+Jaipur',
      },
    ],
    hotels: [
      {
        name: 'LMB Hotel (Laxmi Misthan Bhandar)',
        category: 'Comfort Hotel',
        location: 'Johari Bazaar, Walled City, Jaipur',
        distanceFromSite: '350 meters from Hawa Mahal',
        pricePerNight: '₹4,500 / night',
        priceNumeric: 4500,
        rating: 4.5,
        description: 'Prime location inside the historic jewelry bazaar. Step downstairs right into Jaipur’s most iconic sweet and food emporium.',
        amenities: ['Legendary Restaurant on-site', 'Central Air Conditioning', 'Concierge', 'Room Service'],
        link: 'https://www.hotellmb.com/',
      },
      {
        name: 'Samode Haveli',
        category: 'Heritage Palace',
        location: 'Gangapole, Old City, Jaipur',
        distanceFromSite: '1.8 km from Hawa Mahal',
        pricePerNight: '₹14,500 / night',
        priceNumeric: 14500,
        rating: 4.9,
        description: 'A 225-year-old royal residence with hand-painted archways, mosaic fountains, and a serene Moorish pool.',
        amenities: ['Heritage Spa', 'Mosaic Swimming Pool', 'Elephant Ramp Verandas', 'Fine Dining Dining Room'],
        link: 'https://www.samode.com/samodehaveli/',
      },
      {
        name: 'The Raj Palace Heritage Grand',
        category: 'Heritage Palace',
        location: 'Zorawer Singh Gate, Amer Road, Jaipur',
        distanceFromSite: '2.5 km from Hawa Mahal',
        pricePerNight: '₹18,000 / night',
        priceNumeric: 18000,
        rating: 4.8,
        description: 'Built in 1727, this former royal palace features museum suites, gold-leaf ceilings, and private collections.',
        amenities: ['Private Museum', 'Royal Spa', 'Ayurvedic Wellness', 'Swimming Pool', 'Multi-cuisine Dining'],
        link: 'https://www.rajpalace.com/',
      },
    ],
    restaurants: [
      {
        name: 'Laxmi Misthan Bhandar (LMB Restaurant)',
        cuisine: 'Authentic Rajasthani & Marwari Pure Vegetarian',
        location: 'Johari Bazaar, Jaipur',
        distanceFromSite: '300 meters from Hawa Mahal',
        priceForTwo: '₹600 - ₹900 for two',
        rating: 4.7,
        signatureFoods: ['Royal Rajasthani Thali', 'Pyaaz Ki Kachori', 'Paneer Ghewar', 'Dal Baati Churma', 'Rajbhog'],
        description: 'Operating since 1727, LMB is Jaipur’s culinary temple for authentic ghee-roasted savories and seasonal desserts.',
        link: 'https://maps.google.com/?q=Laxmi+Misthan+Bhandar+Jaipur',
      },
      {
        name: 'The Tattoo Cafe & Lounge',
        cuisine: 'Cafe, North Indian & Continental',
        location: 'Directly Opposite Hawa Mahal (3rd Floor Rooftop), Badi Chaupar',
        distanceFromSite: '40 meters from Hawa Mahal',
        priceForTwo: '₹500 - ₹800 for two',
        rating: 4.6,
        signatureFoods: ['Kulhad Masala Chai', 'Hawa Mahal Sunrise Platter', 'Woodfired Pizza', 'Cold Coffee with Ice Cream'],
        description: 'Spectacular unobstructed rooftop views of Hawa Mahal’s 953 jharokha windows. Ideal for golden hour photography.',
        link: 'https://maps.google.com/?q=The+Tattoo+Cafe+Jaipur+Hawa+Mahal',
      },
      {
        name: 'Rawat Misthan Bhandar',
        cuisine: 'Traditional Rajasthani Snacks & Sweets',
        location: 'Station Road, Sindhi Camp, Jaipur',
        distanceFromSite: '4.1 km from Hawa Mahal',
        priceForTwo: '₹300 - ₹500 for two',
        rating: 4.8,
        signatureFoods: ['Crispy Mawa Kachori', 'Spicy Mirchi Vada', 'Jodhpur Heeng Pyaaz Kachori', 'Rabdi Ghevar'],
        description: 'World-famous for sending thousands of freshly fried mawa and pyaaz kachoris daily across India.',
        link: 'https://maps.google.com/?q=Rawat+Misthan+Bhandar+Jaipur',
      },
    ],
  },

  'taj-mahal': {
    siteId: 'taj-mahal',
    siteName: 'Taj Mahal',
    city: 'Agra',
    state: 'Uttar Pradesh',
    localFoodCulture: 'Synonymous with Mughal imperial gastronomy: slow-cooked Dum biryanis, aromatic saffron kormas, crispy breakfast bedai with spiced potato curry, and world-renowned translucent Agra petha.',
    homestays: [
      {
        name: 'The Coral Tree Homestay',
        location: 'VIP East Gate Road, Taj Nagari, Agra',
        distanceFromSite: '650 meters from Taj Mahal East Gate',
        pricePerNight: '₹2,400 / night',
        priceNumeric: 2400,
        rating: 4.9,
        hostExperience: 'Eco-conscious homestay run by passionate naturalists. Surrounded by bird-friendly flowering trees, offering home-cooked vegetarian North Indian dinners.',
        amenities: ['Lush Eco Garden', 'Home-cooked Breakfast', 'Walk to Taj Mahal Gate', 'High-speed Wi-Fi', 'Bird Watching Terrace'],
        link: 'https://www.thecoraltreehomestay.com/',
      },
      {
        name: 'Aman Homestay',
        location: 'Pawan Dham, Taj Nagari Phase 1, Agra',
        distanceFromSite: '1.2 km from East Gate',
        pricePerNight: '₹1,900 / night',
        priceNumeric: 1900,
        rating: 4.7,
        hostExperience: 'Hosted by Aman and his warm family. Features rooftop terrace with direct views of the Taj Mahal dome at dawn.',
        amenities: ['Rooftop Taj View', 'Cooking Classes', 'Family Dinners', 'Free Wi-Fi', 'Air Conditioning'],
        link: 'https://maps.google.com/?q=Aman+Homestay+Agra',
      },
    ],
    hotels: [
      {
        name: 'The Oberoi Amarvilas',
        category: 'Luxury Resort',
        location: 'Taj East Gate Road, Agra',
        distanceFromSite: '600 meters from Taj Mahal',
        pricePerNight: '₹42,000 / night',
        priceNumeric: 42000,
        rating: 5.0,
        description: 'Every single luxury room and suite has an uninterrupted, direct view of the Taj Mahal. Private golf carts chauffeur guests to the gate.',
        amenities: ['Unrestricted Taj View from Every Room', 'Moorish Terraced Pool', 'Bespoke Spa', 'Fine Dining Mughal Restaurants'],
        link: 'https://www.oberoihotels.com/hotels-in-agra-amarvilas-resort/',
      },
      {
        name: 'ITC Mughal, a Luxury Collection Hotel',
        category: 'Heritage Palace',
        location: 'Fatehabad Road, Tajganj, Agra',
        distanceFromSite: '2.5 km from Taj Mahal',
        pricePerNight: '₹7,500 / night',
        priceNumeric: 7500,
        rating: 4.7,
        description: 'Sprawled across 35 acres of Mughal gardens with tranquil waterways and red-brick courtyards. Home to award-winning Peshawri restaurant.',
        amenities: ['Kaya Kalp Royal Spa', 'Two Swimming Pools', 'Peshawri Dining', 'Jogging Tracks', 'Valet Parking'],
        link: 'https://www.itchotels.com/in/en/itcmughal-agra',
      },
      {
        name: 'Tajview - IHCL SeleQtions',
        category: 'Boutique Hotel',
        location: 'Fatehabad Road, Tajganj, Agra',
        distanceFromSite: '1.8 km from Taj Mahal',
        pricePerNight: '₹5,200 / night',
        priceNumeric: 5200,
        rating: 4.6,
        description: 'Set amidst six acres of landscaped gardens, offering a rooftop lounge overlooking the Taj monument.',
        amenities: ['Rooftop Sky Lounge', 'Outdoor Pool', 'Fitness Center', 'Travel Desk'],
        link: 'https://www.seleqtionshotels.com/',
      },
    ],
    restaurants: [
      {
        name: 'Peshawri at ITC Mughal',
        cuisine: 'North-West Frontier & Tandoor Masterpieces',
        location: 'Fatehabad Road, Agra',
        distanceFromSite: '2.5 km from Taj Mahal',
        priceForTwo: '₹2,500 - ₹4,000 for two',
        rating: 4.9,
        signatureFoods: ['Dal Bukhara (Simmered 18 hours)', 'Sikandari Raan', 'Murgh Malai Kebab', 'Garlic Naan'],
        description: 'Legendary clay tandoor culinary theatre serving Bukhara-style rustic recipes where food is eaten with hands in check aprons.',
        link: 'https://maps.google.com/?q=Peshawri+ITC+Mughal+Agra',
      },
      {
        name: 'Deviram Sweets & Restaurant',
        cuisine: 'Traditional Agra Street Food & Sweets',
        location: 'Pratap Pura, Sadar Bazaar, Agra',
        distanceFromSite: '3.6 km from Taj Mahal',
        priceForTwo: '₹200 - ₹350 for two',
        rating: 4.7,
        signatureFoods: ['Bedai & Spicy Aloo Sabzi', 'Crispy Golden Jalebi with Rabdi', 'Gond Laddoo', 'Kachori'],
        description: 'The definitive morning breakfast ritual in Agra. Crispy puffed lentil puris paired with fiery fenugreek-spiced potato gravy.',
        link: 'https://maps.google.com/?q=Deviram+Sweets+Agra',
      },
      {
        name: 'Panchi Petha Store (Original)',
        cuisine: 'Authentic Agra Confectionery',
        location: 'Hari Parwat / Sadar Bazaar, Agra',
        distanceFromSite: '3.2 km from Taj Mahal',
        priceForTwo: '₹150 - ₹400',
        rating: 4.8,
        signatureFoods: ['Kesar Angoori Petha', 'Chocolate Petha', 'Sandwich Petha', 'Dry Paan Petha', 'Dalmoth Namkeen'],
        description: 'The century-old pioneer of candied ash gourd (petha), once crafted to nourish the royal stonemasons building the Taj Mahal.',
        link: 'https://maps.google.com/?q=Panchi+Petha+Agra',
      },
    ],
  },

  'hampi-ruins': {
    siteId: 'hampi-ruins',
    siteName: 'Hampi Ruins',
    city: 'Vijayanagara',
    state: 'Karnataka',
    localFoodCulture: 'Wholesome North Karnataka rural cuisine: Jowar rotis with stuffed brinjal (Ennegayi), fresh coconut chutneys on banana leaves, and global traveller comfort cafes with herbal teas.',
    homestays: [
      {
        name: 'Mowgli Guest House & Homestay',
        location: 'Sanapur Lake Road, Anegundi (Hippies Island)',
        distanceFromSite: '3.2 km from Vittala Temple (via river crossing)',
        pricePerNight: '₹1,600 / night',
        priceNumeric: 1600,
        rating: 4.7,
        hostExperience: 'Thatched huts amidst paddy fields and towering granite boulders. Chill hammocks, live acoustic jams, and woodfired pizza ovens.',
        amenities: ['Paddy Field View', 'Hammock Chillout Deck', 'Homemade South Indian Meals', 'Bicycle Rentals'],
        link: 'https://maps.google.com/?q=Mowgli+Guest+House+Hampi',
      },
      {
        name: 'Kishkinda Heritage Village Homestay',
        location: 'Near Pampa Sarovar, Anegundi',
        distanceFromSite: '4.5 km from Hampi Bazaar',
        pricePerNight: '₹2,200 / night',
        priceNumeric: 2200,
        rating: 4.6,
        hostExperience: 'Stay inside mythological Kishkindha. Authentic terracotta cottages with local village hosts serving hot thatte idlis.',
        amenities: ['Organic Vegetable Garden', 'Coracle Boat Ride Booking', 'Open-air Verandas', 'Free Breakfast'],
        link: 'https://maps.google.com/?q=Kishkinda+Heritage+Resort+Hampi',
      },
    ],
    hotels: [
      {
        name: 'Evolve Back, Kamalapura Palace',
        category: 'Luxury Resort',
        location: 'Kamalapura, Bellary District, Hampi',
        distanceFromSite: '3.8 km from Vittala Temple',
        pricePerNight: '₹24,000 / night',
        priceNumeric: 24000,
        rating: 5.0,
        description: 'Imposing fortress palace design echoing 14th-century Vijayanagara imperial royal quarters, with stone aqueducts and private Jacuzzi villas.',
        amenities: ['Private Plunge Pools', 'Infinity Pool', 'Vaidyasala Ayurvedic Spa', 'Heritage History Walks'],
        link: 'https://www.evolveback.com/hampi/',
      },
      {
        name: 'Heritage Resort Hampi',
        category: 'Boutique Hotel',
        location: 'Hosapete-Hampi Road, Kamalapura',
        distanceFromSite: '5.5 km from Virupaksha Temple',
        pricePerNight: '₹6,500 / night',
        priceNumeric: 6500,
        rating: 4.7,
        description: 'Eco-conscious villas spread over nine acres of organic mango, coconut, and banana plantations with an outdoor pool.',
        amenities: ['Swimming Pool', 'Organic Multi-cuisine Dining', 'Ayurvedic Center', 'Cycling Tours'],
        link: 'https://www.heritageresortshampi.in/',
      },
    ],
    restaurants: [
      {
        name: 'Mango Tree Restaurant',
        cuisine: 'South Indian, Israeli & Continental',
        location: 'Near Kamalapura / Queens Bath Road, Hampi',
        distanceFromSite: '2.1 km from Virupaksha Temple',
        priceForTwo: '₹350 - ₹700 for two',
        rating: 4.8,
        signatureFoods: ['Banana Leaf Special Thali', 'Banana Flower Curry', 'Falafel Platter', 'Nutella Banoffee Pancake', 'Fresh Mango Lassi'],
        description: 'Hampi’s most famous traveler restaurant. Floor mattress seating, garden ambiance, and generous thalis served on banana leaves.',
        link: 'https://maps.google.com/?q=Mango+Tree+Restaurant+Hampi',
      },
      {
        name: 'Gopi Roof Restaurant',
        cuisine: 'South Indian & Woodfired Pizzas',
        location: 'Hampi Bazaar, Virupaksha Car Street',
        distanceFromSite: '150 meters from Virupaksha Temple',
        priceForTwo: '₹250 - ₹500 for two',
        rating: 4.6,
        signatureFoods: ['Ghee Roast Masala Dosa', 'Thatte Idli with Gunpowder Chutney', 'Jowar Roti with Ennegayi', 'Filter Coffee'],
        description: 'Overlooking Virupaksha Temple gopuram with peaceful vibes and breakfast treats for sunrise explorers.',
        link: 'https://maps.google.com/?q=Gopi+Restaurant+Hampi',
      },
    ],
  },

  'meenakshi-temple': {
    siteId: 'meenakshi-temple',
    siteName: 'Meenakshi Amman Temple',
    city: 'Madurai',
    state: 'Tamil Nadu',
    localFoodCulture: 'Ancient Pandya culinary capital famous for 24-hour street food culture, bun parotta, layered kari dosa, pillow-soft mallipoo idlis, and chilled royal jigarthanda drink.',
    homestays: [
      {
        name: 'Heritage Madurai Villa Homestay',
        location: 'Kochadai, Madurai',
        distanceFromSite: '4.8 km from West Gopuram',
        pricePerNight: '₹3,000 / night',
        priceNumeric: 3000,
        rating: 4.8,
        hostExperience: 'Traditional Chettinad-style pillar courtyard home with swing verandas and freshly ground filter coffee made at dawn.',
        amenities: ['Chettinad Architecture', 'Traditional Breakfast', 'Courtyard Swing', 'Wi-Fi', 'AC Rooms'],
        link: 'https://maps.google.com/?q=Heritage+Madurai',
      },
      {
        name: 'Madurai Residency Homestay',
        location: 'Town Hall Road, Madurai',
        distanceFromSite: '800 meters from South Gopuram',
        pricePerNight: '₹2,100 / night',
        priceNumeric: 2100,
        rating: 4.5,
        hostExperience: 'Located steps away from the bustling temple flower markets. Hosts help arrange VIP temple darshan passes.',
        amenities: ['Walk to Temple', 'Temple Darshan Guidance', 'Air Conditioning', 'Free Wi-Fi'],
        link: 'https://maps.google.com/?q=Madurai+Residency',
      },
    ],
    hotels: [
      {
        name: 'Heritage Madurai',
        category: 'Heritage Palace',
        location: '11 Melakkal Main Road, Kochadai, Madurai',
        distanceFromSite: '5.2 km from Meenakshi Temple',
        pricePerNight: '₹7,200 / night',
        priceNumeric: 7200,
        rating: 4.8,
        description: 'Designed by legendary Sri Lankan architect Geoffrey Bawa, featuring private plunge pool villas and a pool modeled after temple stepped tanks.',
        amenities: ['Temple Tank Pool', 'Bawa Architecture', 'Ayurvedic Spa', 'Banyan Tree Dining'],
        link: 'https://www.heritagemadurai.com/',
      },
      {
        name: 'The Gateway Hotel Pasumalai Madurai',
        category: 'Luxury Resort',
        location: 'Pasumalai Hill, Madurai',
        distanceFromSite: '6.5 km from Meenakshi Temple',
        pricePerNight: '₹6,800 / night',
        priceNumeric: 6800,
        rating: 4.7,
        description: 'A 120-year-old colonial hilltop sanctuary spread across 62 acres of gardens inhabited by dancing peacocks.',
        amenities: ['Hilltop Panoramic Views', 'Swimming Pool', 'Tennis Court', 'Gadaam Bar & Restaurant'],
        link: 'https://www.tajhotels.com/en-in/gateway/pasumalai-madurai/',
      },
    ],
    restaurants: [
      {
        name: 'Murugan Idli Shop (Original)',
        cuisine: 'Traditional Tamil Vegetarian',
        location: 'West Masi Street, Madurai',
        distanceFromSite: '350 meters from West Gopuram',
        priceForTwo: '₹180 - ₹350 for two',
        rating: 4.9,
        signatureFoods: ['Mallipoo Soft Idli', 'Ghee Podi Masala Dosa', 'Onion Uthappam', 'Four Varieties of Fresh Chutney', 'Madurai Degree Filter Coffee'],
        description: 'World-renowned for the fluffiest idlis on earth served over crisp banana leaves with piping hot sambar.',
        link: 'https://maps.google.com/?q=Murugan+Idli+Shop+Madurai',
      },
      {
        name: 'Famous Jigarthanda (Since 1977)',
        cuisine: 'Iconic Madurai Dessert Drink',
        location: 'East Marret Street, Near Clock Tower, Madurai',
        distanceFromSite: '700 meters from East Gopuram',
        priceForTwo: '₹80 - ₹160',
        rating: 4.9,
        signatureFoods: ['Royal Special Jigarthanda', 'Basundi Ice Cream', 'Dry Fruit Jigarthanda'],
        description: 'Madurai’s legendary coolant crafted with almond gum (badam pisin), nannari herbal root syrup, condensed reduced milk, and basundi ice cream.',
        link: 'https://maps.google.com/?q=Famous+Jigarthanda+Madurai',
      },
      {
        name: 'Amma Mess',
        cuisine: 'Iconic Madurai Non-Vegetarian & Chettinad',
        location: 'Alagar Kovil Road, Madurai',
        distanceFromSite: '3.4 km from Meenakshi Temple',
        priceForTwo: '₹400 - ₹850 for two',
        rating: 4.7,
        signatureFoods: ['Mutton Kari Dosa (Triple Decker)', 'Bone Marrow Omelette (Nalli Omelette)', 'Fish Head Curry (Meen Kuzhambu)', 'Pallipalayam Chicken'],
        description: 'Celebrated on national television for creating the viral three-layered Kari Dosa topped with minced mutton and egg.',
        link: 'https://maps.google.com/?q=Amma+Mess+Madurai',
      },
    ],
  },

  'ajanta-caves': {
    siteId: 'ajanta-caves',
    siteName: 'Ajanta Caves',
    city: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    localFoodCulture: 'Hearty Khandeshi and Marathwada fare: fiery Shev Bhaji, Jowar Bhakri, Pitla with green chili Thecha, and Aurangabadi Naan Qalia.',
    homestays: [
      {
        name: 'Ajanta Farmstay & Organic Retreat',
        location: 'Fardapur Village, Near Ajanta Caves',
        distanceFromSite: '3.8 km from Caves T-Junction',
        pricePerNight: '₹1,800 / night',
        priceNumeric: 1800,
        rating: 4.7,
        hostExperience: 'Cotton and pomegranate farm hosted by a local agrarian family. Home-churned white butter, bajra bhakri, and bonfire dinners.',
        amenities: ['Farm Tour', 'Organic Home Cooking', 'Rural Stargazing', 'Free Wi-Fi', 'Hot Showers'],
        link: 'https://maps.google.com/?q=Fardapur+Ajanta+Homestay',
      },
      {
        name: 'Green Valley Homestay',
        location: 'Lenapur, Aurangabad District',
        distanceFromSite: '4.5 km from Cave Entrance',
        pricePerNight: '₹1,500 / night',
        priceNumeric: 1500,
        rating: 4.5,
        hostExperience: 'Rustic quiet retreat with mountain views of Waghora gorge hills.',
        amenities: ['Valley View', 'Authentic Maharashtrian Thali', 'Bicycle Hire', 'Free Parking'],
        link: 'https://maps.google.com/?q=Lenapur+Ajanta',
      },
    ],
    hotels: [
      {
        name: 'MTDC Holiday Resort Fardapur',
        category: 'Comfort Hotel',
        location: 'Fardapur, Aurangabad-Jalgaon Road',
        distanceFromSite: '4.0 km from Ajanta Caves Entrance',
        pricePerNight: '₹2,200 / night',
        priceNumeric: 2200,
        rating: 4.4,
        description: 'Official Maharashtra Tourism development corporation resort. Dedicated eco-friendly shuttles directly to the caves entrance.',
        amenities: ['Restaurant & Bar', 'Spacious Lawns', 'Cave Shuttle Access', 'Conference Hall'],
        link: 'https://www.maharashtratourism.gov.in/',
      },
      {
        name: 'Vivanta Aurangabad',
        category: 'Luxury Resort',
        location: '8-N-12, Cidco, Chhatrapati Sambhajinagar (Base City)',
        distanceFromSite: '98 km from Ajanta Caves (Major Transit Hub)',
        pricePerNight: '₹8,500 / night',
        priceNumeric: 8500,
        rating: 4.8,
        description: 'Palace-styled retreat surrounded by 5 acres of gardens, the premier luxury base for exploring Ajanta and Ellora caves.',
        amenities: ['Swimming Pool', 'Fine Dining Tease Bar', 'Luxury Spa', 'Travel Desk for Cave Chauffeur'],
        link: 'https://www.vivantahotels.com/',
      },
    ],
    restaurants: [
      {
        name: 'MTDC Restaurant & Garden Dhaba',
        cuisine: 'Maharashtrian & North Indian',
        location: 'Fardapur Resort Campus, Ajanta',
        distanceFromSite: '3.9 km from Caves',
        priceForTwo: '₹300 - ₹600 for two',
        rating: 4.5,
        signatureFoods: ['Khandeshi Kala Masala Shev Bhaji', 'Jowar Bhakri with Thecha', 'Pithla Bhat', 'Shrikhand'],
        description: 'Wholesome local Maharashtrian meal served right before boarding the eco-bus to the basalt rock caves.',
        link: 'https://maps.google.com/?q=MTDC+Fardapur+Restaurant',
      },
      {
        name: 'Bhoj Restaurant (Base Transit)',
        cuisine: 'Traditional Gujarati & Maharashtrian Thali',
        location: 'Near CBS, Chhatrapati Sambhajinagar',
        distanceFromSite: 'City transit hub',
        priceForTwo: '₹350 - ₹600 for two',
        rating: 4.7,
        signatureFoods: ['Unlimited Royal Thali', 'Aamras Puri (Seasonal)', 'Kadhi Khichdi', 'Dal Baati'],
        description: 'Beloved city eatery serving unlimited wholesome thalis with over 20 home-style delicacies.',
        link: 'https://maps.google.com/?q=Bhoj+Restaurant+Aurangabad',
      },
    ],
  },

  'mattancherry-palace': {
    siteId: 'mattancherry-palace',
    siteName: 'Mattancherry Palace',
    city: 'Kochi',
    state: 'Kerala',
    localFoodCulture: 'Spice-scented Malabar coast recipes: coconut milk Alleppey fish curry, flaky Kerala parottas, appam with vegetable stew, and aromatic Kayees mutton biryani.',
    homestays: [
      {
        name: 'Riva Heritage Homestay',
        location: 'Jew Town, Mattancherry, Kochi',
        distanceFromSite: '350 meters from Mattancherry Palace',
        pricePerNight: '₹2,200 / night',
        priceNumeric: 2200,
        rating: 4.8,
        hostExperience: 'Centuries-old Dutch-Jewish townhouse in the antique market with teak wood beams and fragrant spice courtyards.',
        amenities: ['Walk to Palace', 'Antique Shopping Access', 'Free Wi-Fi', 'Traditional Kerala Breakfast'],
        link: 'https://maps.google.com/?q=Jew+Town+Homestay+Kochi',
      },
      {
        name: 'Secret Garden A Boutique Homestay',
        location: 'Princess Street, Fort Kochi',
        distanceFromSite: '2.8 km from Palace',
        pricePerNight: '₹4,500 / night',
        priceNumeric: 4500,
        rating: 4.9,
        hostExperience: 'Architectural gem with courtyard swimming pool, organic yoga terrace, and host cooking sessions.',
        amenities: ['Courtyard Pool', 'Ayurvedic Massage', 'Yoga Classes', 'Air Conditioning'],
        link: 'https://maps.google.com/?q=Secret+Garden+Fort+Kochi',
      },
    ],
    hotels: [
      {
        name: 'Brunton Boatyard - CGH Earth',
        category: 'Heritage Palace',
        location: '1/498, Calvathy, Fort Kochi',
        distanceFromSite: '2.4 km from Mattancherry Palace',
        pricePerNight: '₹18,000 / night',
        priceNumeric: 18000,
        rating: 4.9,
        description: 'A restored Victorian shipyard hotel built with lime plaster, terracotta floors, and antique punkah fans overlooking shipping channels.',
        amenities: ['Waterfront Harbor View', 'History of Spice Route Menu', 'Sunset Cruise', 'Swimming Pool'],
        link: 'https://www.cghearth.com/brunton-boatyard',
      },
      {
        name: 'The Malabar House',
        category: 'Boutique Hotel',
        location: '1/268, Parade Ground, Fort Kochi',
        distanceFromSite: '2.7 km from Mattancherry Palace',
        pricePerNight: '₹9,500 / night',
        priceNumeric: 9500,
        rating: 4.8,
        description: 'First boutique heritage hotel in Fort Kochi combining 18th-century Dutch architecture with contemporary Indian art.',
        amenities: ['Art Collection Gallery', 'Wine Bar', 'Ayurveda Pura Spa', 'Lap Pool'],
        link: 'https://www.malabarhouse.com/',
      },
    ],
    restaurants: [
      {
        name: 'Ginger House Restaurant',
        cuisine: 'Seafood, Malabar & Continental',
        location: 'Jew Town, Mattancherry (Inside Heritage Arts)',
        distanceFromSite: '300 meters from Palace',
        priceForTwo: '₹700 - ₹1,300 for two',
        rating: 4.7,
        signatureFoods: ['Signature Ginger Ice Cream', 'Alleppey Fish Curry in Claypot', 'Appam with Stew', 'Tiger Prawn Roast'],
        description: 'Dine right on the waterfront overlooking historic boats, housed inside India’s largest antique showroom.',
        link: 'https://maps.google.com/?q=Ginger+House+Restaurant+Kochi',
      },
      {
        name: 'Kayees Rahmathulla Hotel',
        cuisine: 'Legendary Malabar Dum Biryani',
        location: 'Mattancherry, Kochi',
        distanceFromSite: '750 meters from Palace',
        priceForTwo: '₹350 - ₹650 for two',
        rating: 4.8,
        signatureFoods: ['Malabar Mutton Dum Biryani', 'Kochi Chicken Fry', 'Date & Lemon Pickle', 'Sulaimani Black Tea'],
        description: 'Kochi’s most celebrated biryani institution since 1948. Long-grain fragrant rice dum-cooked with tender spiced mutton.',
        link: 'https://maps.google.com/?q=Kayees+Rahmathulla+Hotel+Mattancherry',
      },
    ],
  },

  'mehrangarh-fort': {
    siteId: 'mehrangarh-fort',
    siteName: 'Mehrangarh Fort',
    city: 'Jodhpur',
    state: 'Rajasthan',
    localFoodCulture: 'Fierce Marwar flavors: rich fiery Laal Maas (red mutton curry with Mathania chilies), desert Ker Sangri, Pyaaz ki kachori, and saffron Makhaniya lassi.',
    homestays: [
      {
        name: 'The Blue House Homestay',
        location: 'Moti Chowk, Old Blue City, Jodhpur',
        distanceFromSite: '700 meters from Fort Gate',
        pricePerNight: '₹2,200 / night',
        priceNumeric: 2200,
        rating: 4.8,
        hostExperience: 'A 500-year-old family haveli painted in royal indigo blue. The rooftop terrace feels so close to Mehrangarh’s battlements you could almost touch them.',
        amenities: ['Indigo Blue Haveli', 'Fort View Rooftop', 'Family Home Meals', 'Free Wi-Fi', 'Walking Tours'],
        link: 'https://maps.google.com/?q=The+Blue+House+Jodhpur',
      },
      {
        name: 'Haveli Inn Pal',
        location: 'Opposite Gulab Sagar, Clock Tower, Jodhpur',
        distanceFromSite: '1.1 km from Fort',
        pricePerNight: '₹3,400 / night',
        priceNumeric: 3400,
        rating: 4.7,
        hostExperience: 'Restored lakeside family residence of the Pal Thakur family. Overlooks Gulab Sagar lake with sweeping fort views.',
        amenities: ['Lake & Fort View', 'Antique Rajput Decor', 'Rooftop Restaurant', 'Air Conditioning'],
        link: 'https://maps.google.com/?q=Haveli+Inn+Pal+Jodhpur',
      },
    ],
    hotels: [
      {
        name: 'RAAS Jodhpur',
        category: 'Heritage Palace',
        location: 'Tunwar ji ka Jhalra, Makrana Mohalla, Jodhpur',
        distanceFromSite: '600 meters from Fort',
        pricePerNight: '₹22,000 / night',
        priceNumeric: 22000,
        rating: 4.9,
        description: 'Built around an 18th-century stepwell directly beneath Mehrangarh Fort. Red sandstone architecture with heated pool.',
        amenities: ['Direct Cliffside Fort View', 'Heated Outdoor Pool', 'Stepwell Terrace Bar', 'Ila Spa'],
        link: 'https://www.raashotels.com/jodhpur/',
      },
      {
        name: 'Umaid Bhawan Palace',
        category: 'Heritage Palace',
        location: 'Circuit House Road, Jodhpur',
        distanceFromSite: '5.6 km from Mehrangarh Fort',
        pricePerNight: '₹55,000 / night',
        priceNumeric: 55000,
        rating: 5.0,
        description: 'One of the world’s largest private residences, home to the former Maharaja of Jodhpur, built from golden Chittar sandstone.',
        amenities: ['Palace Museum', 'Subterranean Zodiac Pool', 'Jiva Grande Spa', 'Peacock Gardens'],
        link: 'https://www.tajhotels.com/en-in/taj/umaid-bhawan-palace-jodhpur/',
      },
    ],
    restaurants: [
      {
        name: 'Chokelao Restaurant (Inside Fort Ramparts)',
        cuisine: 'Royal Rajasthani Fine Dining',
        location: 'Mehrangarh Fort Upper Courtyard, Jodhpur',
        distanceFromSite: '0 meters (Inside Fort)',
        priceForTwo: '₹1,200 - ₹2,500 for two',
        rating: 4.8,
        signatureFoods: ['Royal Marwar Thali', 'Mathania Laal Maas', 'Gatte Ki Khichdi', 'Ker Sangri Ro Faliyan', 'Malpua'],
        description: 'Dine in open-air terrace under the illuminated ramparts of the fort with the twinkling blue city spread 400 feet below.',
        link: 'https://maps.google.com/?q=Chokelao+Mehrangarh+Fort',
      },
      {
        name: 'Shri Mishrilal Hotel',
        cuisine: 'Legendary Saffron Lassi',
        location: 'Sardar Market Clock Tower, Jodhpur',
        distanceFromSite: '950 meters from Fort',
        priceForTwo: '₹100 - ₹200',
        rating: 4.9,
        signatureFoods: ['Original Makhaniya Lassi', 'Rabdi Ghewar', 'Mawa Kachori', 'Gulab Jamun'],
        description: 'Serving Jodhpur’s most famous thick saffron lassi since 1927, topped with fresh clotted malai and cardamom.',
        link: 'https://maps.google.com/?q=Mishrilal+Lassi+Jodhpur',
      },
      {
        name: 'Janta Sweet Home',
        cuisine: 'Rajasthani Street Snacks & Thalis',
        location: 'Nai Sarak, Near Clock Tower, Jodhpur',
        distanceFromSite: '1.2 km from Fort',
        priceForTwo: '₹250 - ₹450 for two',
        rating: 4.7,
        signatureFoods: ['Spicy Mirchi Bada', 'Pyaaz Kachori', 'Kaju Katli', 'Mawa Paan'],
        description: 'Crowded local hotspot churning out hundreds of freshly fried spicy green chili fritters (Mirchi Badas) per hour.',
        link: 'https://maps.google.com/?q=Janta+Sweet+Home+Jodhpur',
      },
    ],
  },

  'konark-sun-temple': {
    siteId: 'konark-sun-temple',
    siteName: 'Konark Sun Temple',
    city: 'Konark',
    state: 'Odisha',
    localFoodCulture: 'Coastal Odia temple delicacies: Dalma with roasted cumin, mustard fish curry (Machha Besara), Chhena Poda (baked caramelized cottage cheese), and fresh Bay of Bengal crab.',
    homestays: [
      {
        name: 'Labanya Lodge & Homestay',
        location: 'Sun Temple Main Road, Konark',
        distanceFromSite: '750 meters from Konark Sun Temple',
        pricePerNight: '₹1,400 / night',
        priceNumeric: 1400,
        rating: 4.6,
        hostExperience: 'Warm family lodge surrounded by coconut groves. The host family cooks fresh Bay of Bengal sea fish curries on order.',
        amenities: ['Walking Distance to Temple', 'Homemade Odia Meals', 'Free Parking', 'Bicycle Rentals'],
        link: 'https://maps.google.com/?q=Labanya+Lodge+Konark',
      },
      {
        name: 'Surya Inn Homestay',
        location: 'Near Helipad Ground, Konark',
        distanceFromSite: '1.0 km from Temple',
        pricePerNight: '₹1,700 / night',
        priceNumeric: 1700,
        rating: 4.5,
        hostExperience: 'Quiet rooms with garden veranda, peaceful location for dawn visits to the Sun Temple wheels.',
        amenities: ['Garden Veranda', 'AC Rooms', 'Wi-Fi', 'Local Tour Guides'],
        link: 'https://maps.google.com/?q=Surya+Inn+Konark',
      },
    ],
    hotels: [
      {
        name: 'Lotus Eco Beach Resort Konark',
        category: 'Luxury Resort',
        location: 'Ramchandi Beach, Konark',
        distanceFromSite: '6.2 km from Sun Temple',
        pricePerNight: '₹5,500 / night',
        priceNumeric: 5500,
        rating: 4.7,
        description: 'Eco-friendly wooden pine cottages situated where the Kushabhadra river mouth joins the Bay of Bengal.',
        amenities: ['Private Beachfront Access', 'Ayurvedic Spa', 'Water Sports', 'Riverfront Dining'],
        link: 'https://maps.google.com/?q=Lotus+Eco+Resort+Konark',
      },
      {
        name: 'Mayfair Waves Puri',
        category: 'Luxury Resort',
        location: 'Chakratirtha Road, Puri',
        distanceFromSite: '32 km from Konark (Coastal Marine Drive)',
        pricePerNight: '₹11,000 / night',
        priceNumeric: 11000,
        rating: 4.9,
        description: 'Premier seaside luxury resort overlooking Golden Beach, perfect base along the Konark Marine Drive.',
        amenities: ['Beachfront Infinity Pool', 'Spa by the Sea', 'Samudra Multi-cuisine', 'Private Cabanas'],
        link: 'https://www.mayfairhotels.com/mayfair-waves-puri/',
      },
    ],
    restaurants: [
      {
        name: 'OTDC Yatrinivas Restaurant',
        cuisine: 'Traditional Odia & Seafood',
        location: 'Opposite Sun Temple Entrance, Konark',
        distanceFromSite: '250 meters from Temple Gate',
        priceForTwo: '₹300 - ₹600 for two',
        rating: 4.5,
        signatureFoods: ['Odia Thali with Dalma', 'Machha Besara (Fish in Mustard Gravy)', 'Crab Kalia', 'Chhena Poda'],
        description: 'Government tourism restaurant offering hygienic, reliable authentic Odia temple and coastal seafood meals.',
        link: 'https://maps.google.com/?q=OTDC+Yatrinivas+Konark',
      },
      {
        name: 'Nimapada Chhena Poda Stalls',
        cuisine: 'Traditional Odia Confectionery',
        location: 'Konark-Nimapada Road',
        distanceFromSite: 'En route Konark',
        priceForTwo: '₹100 - ₹250',
        rating: 4.9,
        signatureFoods: ['Smoky Baked Chhena Poda', 'Chhena Gaja', 'Rasabali', 'Khira Gaja'],
        description: 'World-famous caramelized cottage cheese dessert slow-baked overnight inside wrapped sal leaves over charcoal embers.',
        link: 'https://maps.google.com/?q=Nimapada+Chhena+Poda',
      },
    ],
  },

  'khajuraho-temples': {
    siteId: 'khajuraho-temples',
    siteName: 'Khajuraho Temples',
    city: 'Chhatarpur',
    state: 'Madhya Pradesh',
    localFoodCulture: 'Rustic Bundelkhandi specialties: Mawa Jalebi, rich Khoya Bati, Bafla with spicy dal, roasted makhana, and rooftop heritage cafes.',
    homestays: [
      {
        name: 'Headquarter Khajuraho Homestay',
        location: 'Sevagram, Near Western Group of Temples',
        distanceFromSite: '650 meters from Western Group',
        pricePerNight: '₹1,500 / night',
        priceNumeric: 1500,
        rating: 4.8,
        hostExperience: 'Hosted by local historians. Enjoy home-cooked Bundelkhandi dishes and rooftop view of temple spires.',
        amenities: ['Rooftop Temple View', 'Home Kitchen Thalis', 'Bicycle Tours', 'Free Wi-Fi'],
        link: 'https://maps.google.com/?q=Headquarter+Homestay+Khajuraho',
      },
      {
        name: 'Friends In Khajuraho Homestay',
        location: 'Old Village, Khajuraho',
        distanceFromSite: '900 meters from Temples',
        pricePerNight: '₹1,300 / night',
        priceNumeric: 1300,
        rating: 4.6,
        hostExperience: 'Eco-cottages with clay plastering in the quiet village quarter with family cooking lessons.',
        amenities: ['Quiet Village Setting', 'Cooking Lessons', 'Garden Terrace', 'Wi-Fi'],
        link: 'https://maps.google.com/?q=Friends+In+Khajuraho',
      },
    ],
    hotels: [
      {
        name: 'The Lalit Temple View Khajuraho',
        category: 'Luxury Resort',
        location: 'Opposite Western Group of Temples, Khajuraho',
        distanceFromSite: '400 meters from Western Group',
        pricePerNight: '₹8,500 / night',
        priceNumeric: 8500,
        rating: 4.8,
        description: 'Direct view of the 10th-century Chandela temples from lush landscaped gardens. Nightly sound and light show nearby.',
        amenities: ['Direct Temple View Lawns', 'Outdoor Pool', 'Rejuve Spa', 'Panna National Park Safari Desk'],
        link: 'https://www.thelalit.com/the-lalit-khajuraho/',
      },
      {
        name: 'Radisson Jass Hotel Khajuraho',
        category: 'Comfort Hotel',
        location: 'By Pass Road, Khajuraho',
        distanceFromSite: '1.8 km from Western Group',
        pricePerNight: '₹5,200 / night',
        priceNumeric: 5200,
        rating: 4.7,
        description: 'Set on serene landscaped grounds with pool and dining rooms serving royal Bundeli cuisine.',
        amenities: ['Swimming Pool', 'Fitness Center', 'Temple Tour Shuttle', 'Buffet Dining'],
        link: 'https://www.radissonhotels.com/',
      },
    ],
    restaurants: [
      {
        name: "Raja's Cafe",
        cuisine: 'Swiss, Indian & Continental',
        location: 'Main Road, Directly Opposite Western Group Gates',
        distanceFromSite: '80 meters from Western Group entrance',
        priceForTwo: '₹400 - ₹800 for two',
        rating: 4.7,
        signatureFoods: ['Swiss Rosti with Cheese', 'Bundelkhandi Veg Thali', 'Espresso Coffee', 'Apple Strudel with Custard'],
        description: 'Founded in 1978 by two Swiss sisters and local brothers. Tree-shaded open terrace directly facing the ancient temple entrance.',
        link: 'https://maps.google.com/?q=Rajas+Cafe+Khajuraho',
      },
      {
        name: 'Badri Seth Misthan Bhandar',
        cuisine: 'Traditional Bundelkhandi Sweets',
        location: 'Main Market, Khajuraho',
        distanceFromSite: '500 meters from Temple',
        priceForTwo: '₹150 - ₹300',
        rating: 4.8,
        signatureFoods: ['Hot Jalebi with Creamy Rabdi', 'Mawa Bati', 'Khoya Jalebi', 'Samose with Chutney'],
        description: 'Beloved morning pitstop for thick, crispy jalebis dipped in pure desi ghee.',
        link: 'https://maps.google.com/?q=Badri+Seth+Khajuraho',
      },
    ],
  },

  'golden-temple': {
    siteId: 'golden-temple',
    siteName: 'Harmandir Sahib (Golden Temple)',
    city: 'Amritsar',
    state: 'Punjab',
    localFoodCulture: 'The world’s culinary capital of generosity: sacred Langar community feasts, flaky tandoori Amritsari kulchas filled with spiced potatoes, 24-hour slow-cooked Dal Makhani at Kesar, and creamy saffron lassi in earthen kulhads.',
    homestays: [
      {
        name: 'Amritsar Heritage Farmstay',
        location: 'Verka Outskirts, Amritsar',
        distanceFromSite: '7.5 km from Golden Temple',
        pricePerNight: '₹2,500 / night',
        priceNumeric: 2500,
        rating: 4.9,
        hostExperience: 'Authentic Punjabi pind farm lifestyle. Tractor rides through mustard fields, organic milk from family cows, and tandoori rotis.',
        amenities: ['Mustard Farm Experience', 'Tractor Rides', 'Organic Punjabi Meals', 'Bicycle Tours'],
        link: 'https://maps.google.com/?q=Amritsar+Farmstay',
      },
      {
        name: 'Virasat Heritage Homestay',
        location: 'Near Town Hall / Heritage Street, Amritsar',
        distanceFromSite: '450 meters from Golden Temple',
        pricePerNight: '₹1,800 / night',
        priceNumeric: 1800,
        rating: 4.7,
        hostExperience: 'Walk down the pedestrianized Heritage Street right to the golden sanctum in 5 minutes.',
        amenities: ['Walk to Golden Temple', 'Air Conditioning', 'Punjabi Breakfast', 'Free Wi-Fi'],
        link: 'https://maps.google.com/?q=Town+Hall+Amritsar+Homestay',
      },
    ],
    hotels: [
      {
        name: 'Hyatt Regency Amritsar',
        category: 'Luxury Resort',
        location: 'MBM Farms, GT Road, Amritsar',
        distanceFromSite: '4.5 km from Golden Temple',
        pricePerNight: '₹6,500 / night',
        priceNumeric: 6500,
        rating: 4.8,
        description: '5-star luxury hotel offering complimentary luxury coach shuttles throughout the day to the Golden Temple.',
        amenities: ['Complimentary Golden Temple Shuttle', 'Outdoor Vitality Pool', 'Shanti Spa', 'Punjab Province Dining'],
        link: 'https://www.hyatt.com/',
      },
      {
        name: 'Radisson Blu Hotel Amritsar',
        category: 'Comfort Hotel',
        location: 'Airport Road, Amritsar',
        distanceFromSite: '10.5 km from Golden Temple',
        pricePerNight: '₹5,800 / night',
        priceNumeric: 5800,
        rating: 4.7,
        description: 'Contemporary comfort with landscaped gardens and gourmet restaurants.',
        amenities: ['Swimming Pool', 'Airport Shuttle', 'Fine Dining Tavolo Mondo', 'Free Wi-Fi'],
        link: 'https://www.radissonhotels.com/',
      },
    ],
    restaurants: [
      {
        name: 'Guru Ka Langar (World Largest Community Kitchen)',
        cuisine: 'Sacred Egalitarian Vegetarian Seva',
        location: 'Inside Sri Harmandir Sahib Complex',
        distanceFromSite: '0 meters (Inside Temple Complex)',
        priceForTwo: 'Free / Selfless Service (Voluntary Seva)',
        rating: 5.0,
        signatureFoods: ['Dal Makhani (Simmered in giant cauldrons)', 'Fresh Hand-rolled Tandoori Rotis', 'Kheer (Rice Pudding)', 'Sacred Karah Prasad (Halwa with Ghee)'],
        description: 'Feeds over 100,000 pilgrims every single day without distinction of caste, religion, or wealth. The purest culinary expression of equality and devotion.',
        link: 'https://maps.google.com/?q=Golden+Temple+Langar+Amritsar',
      },
      {
        name: 'Bhai Kulwant Singh Kulchian Wale',
        cuisine: 'World-Famous Amritsari Kulcha',
        location: 'Bazar Bikanerian, Near Heritage Street, Amritsar',
        distanceFromSite: '350 meters from Golden Temple',
        priceForTwo: '₹150 - ₹300 for two',
        rating: 4.9,
        signatureFoods: ['Crispy Aloo Chur-Chur Kulcha', 'Paneer Pyaaz Kulcha', 'Spicy Chole with Tamarind Onion Chutney', 'Desi Ghee Chashni'],
        description: 'Baked inside red-hot underground clay tandoors until shattering and layered with pure country butter.',
        link: 'https://maps.google.com/?q=Bhai+Kulwant+Singh+Kulcha+Amritsar',
      },
      {
        name: 'Kesar Da Dhaba (Since 1916)',
        cuisine: 'Legendary Punjabi Dhaba Heritage',
        location: 'Chowk Passian, Near Telephone Exchange, Amritsar',
        distanceFromSite: '750 meters from Golden Temple',
        priceForTwo: '₹350 - ₹700 for two',
        rating: 4.8,
        signatureFoods: ['Maa Ki Dal (Slow-cooked for 24 hours)', 'Laccha Paratha in Ghee', 'Baigan Bharta', 'Firni in Earthen Kasora'],
        description: 'Established over a century ago in 1916, where Lala Kesar Mal fed freedom fighters and generations of food lovers.',
        link: 'https://maps.google.com/?q=Kesar+Da+Dhaba+Amritsar',
      },
    ],
  },

  'madhubani-art': {
    siteId: 'madhubani-art',
    siteName: 'Mithila Madhubani Traditions',
    city: 'Mithila',
    state: 'Bihar',
    localFoodCulture: 'Classic Bihari & Maithil cuisine: roasted gram flour Litti Chokha drenched in pure ghee, delicate Makhana kheer, and mustard-scented freshwater fish curry.',
    homestays: [
      {
        name: 'Ranti Artists Village Homestay',
        location: 'Ranti Village, Madhubani',
        distanceFromSite: '3.0 km from Madhubani District Center',
        pricePerNight: '₹1,600 / night',
        priceNumeric: 1600,
        rating: 4.9,
        hostExperience: 'Live directly with National Award-winning women artists. Paint with natural bamboo nibs and botanical dyes alongside village masters.',
        amenities: ['Art Workshop Access', 'Traditional Mud Architecture', 'Organic Maithil Thali', 'Village Strolls'],
        link: 'https://maps.google.com/?q=Ranti+Village+Madhubani',
      },
      {
        name: 'Jitwarpur Master Crafts Homestay',
        location: 'Jitwarpur Village, Madhubani',
        distanceFromSite: '4.2 km from City Center',
        pricePerNight: '₹1,400 / night',
        priceNumeric: 1400,
        rating: 4.7,
        hostExperience: 'Cottages hand-painted with auspicious Kohbar wedding murals on cow-dung plaster walls.',
        amenities: ['Hand-painted Cottages', 'Home-cooked Meals', 'Artisan Souvenir Shop', 'Friendly Village Guides'],
        link: 'https://maps.google.com/?q=Jitwarpur+Madhubani',
      },
    ],
    hotels: [
      {
        name: 'Hotel Sagar Residency',
        category: 'Comfort Hotel',
        location: 'Station Road, Madhubani Town',
        distanceFromSite: '1.8 km from Railway Junction',
        pricePerNight: '₹2,200 / night',
        priceNumeric: 2200,
        rating: 4.3,
        description: 'Modern comfortable rooms in the heart of town with easy transport to Ranti and Jitwarpur craft villages.',
        amenities: ['Air Conditioning', 'In-house Restaurant', 'Free Wi-Fi', 'Car Rental Desk'],
        link: 'https://maps.google.com/?q=Hotel+Sagar+Madhubani',
      },
    ],
    restaurants: [
      {
        name: 'Mithila Bhojnalaya',
        cuisine: 'Traditional Maithil & Bihari Thali',
        location: 'Station Road, Madhubani',
        distanceFromSite: '1.5 km from Center',
        priceForTwo: '₹200 - ₹400 for two',
        rating: 4.6,
        signatureFoods: ['Traditional Litti Chokha with Ghee', 'Freshwater Machh-Bhaat (Rohu Fish Curry)', 'Makhana Kheer', 'Tilba Sweet'],
        description: 'Authentic local dining where sattu-stuffed littis are roasted over wood ash and served with charred eggplant chokha.',
        link: 'https://maps.google.com/?q=Madhubani+Station+Eateries',
      },
    ],
  },

  'durga-puja-kolkata': {
    siteId: 'durga-puja-kolkata',
    siteName: 'Durga Puja of Kolkata',
    city: 'Kolkata',
    state: 'West Bengal',
    localFoodCulture: 'A continuous gastronomic festival: spicy Kolkata Kathi rolls, Daab Chingri (prawns cooked in green coconut), Kosha Mangsho with hot luchis, and delicate mishti like Jolbhora Sandesh.',
    homestays: [
      {
        name: 'Calcutta Bungalow',
        location: '5 Fariapukur, Shyambazar, North Kolkata',
        distanceFromSite: '2.2 km from Kumartuli Potter Town',
        pricePerNight: '₹5,500 / night',
        priceNumeric: 5500,
        rating: 4.9,
        hostExperience: '1920s townhouse restored into a living heritage museum with rooms named after heritage trades: Weaver, Jute, Boi-Para.',
        amenities: ['1920s Heritage Townhouse', 'Vintage Bicycles', 'Courtyard Breakfast', 'Free High-speed Wi-Fi'],
        link: 'https://www.calcuttabungalow.com/',
      },
      {
        name: 'Laha Bari Guest Suite',
        location: 'Beadon Street, North Kolkata',
        distanceFromSite: '1.2 km from Kumartuli',
        pricePerNight: '₹3,200 / night',
        priceNumeric: 3200,
        rating: 4.7,
        hostExperience: 'Stay inside a historic 18th-century aristocratic Rajbari mansion that celebrates one of Kolkata’s oldest household pujas.',
        amenities: ['Aristocratic Rajbari Estate', 'Courtyard Pandal View', 'Bengali Homestyle Cooking'],
        link: 'https://maps.google.com/?q=Laha+Bari+Kolkata',
      },
    ],
    hotels: [
      {
        name: 'The Oberoi Grand Kolkata',
        category: 'Heritage Palace',
        location: '15 Jawaharlal Nehru Road, New Market, Kolkata',
        distanceFromSite: '4.5 km from North Kolkata Pandals',
        pricePerNight: '₹12,000 / night',
        priceNumeric: 12000,
        rating: 4.9,
        description: 'Known as the "Grande Dame of Chowringhee", this Victorian colonial palace hotel features a palm-fringed pool and heritage ballrooms.',
        amenities: ['Palm-fringed Pool', 'Baan Thai Fine Dining', 'Oberoi Spa', 'Heritage High Tea'],
        link: 'https://www.oberoihotels.com/hotels-in-kolkata/',
      },
      {
        name: 'The Lalit Great Eastern Kolkata',
        category: 'Heritage Palace',
        location: '1, 2 & 3 Old Court House Street, Dalhousie Square, Kolkata',
        distanceFromSite: '3.5 km from College Street',
        pricePerNight: '₹7,500 / night',
        priceNumeric: 7500,
        rating: 4.7,
        description: 'Asia’s oldest continuously operating luxury hotel, dating back to 1840 during the British East India Company era.',
        amenities: ['Rejuve Spa', 'Heritage Bakery on-site', 'Outdoor Pool', 'Victorian Architecture'],
        link: 'https://www.thelalit.com/the-lalit-kolkata/',
      },
    ],
    restaurants: [
      {
        name: '6 Ballygunge Place',
        cuisine: 'Authentic Zamindari Bengali Cuisine',
        location: '6 Ballygunge Place / Salt Lake, Kolkata',
        distanceFromSite: '4.8 km from City Center',
        priceForTwo: '₹800 - ₹1,500 for two',
        rating: 4.8,
        signatureFoods: ['Daab Chingri (Prawns in Tender Coconut)', 'Kosha Mangsho with Luchi', 'Chitol Machher Muitha', 'Bhetki Paturi in Banana Leaf', 'Baked Rosogolla'],
        description: 'Set inside a restored 100-year-old colonial bungalow, celebrating royal recipes recorded in ancestral Bengali cookbooks.',
        link: 'https://maps.google.com/?q=6+Ballygunge+Place+Kolkata',
      },
      {
        name: 'Mitra Cafe (Since 1920)',
        cuisine: 'Iconic North Kolkata Heritage Snacks',
        location: '47 Jatindra Mohan Avenue, Shobhabazar',
        distanceFromSite: '700 meters from Kumartuli',
        priceForTwo: '₹250 - ₹450 for two',
        rating: 4.8,
        signatureFoods: ['Mutton Diamond Fry', 'Brain Chop', 'Fish Kabiraji with Kasundi Mustard', 'Chicken Roll'],
        description: 'The epicenter of North Kolkata’s century-old cabin food culture, famous for crispy egg-mesh coated cutlets.',
        link: 'https://maps.google.com/?q=Mitra+Cafe+Shobhabazar',
      },
      {
        name: 'Girish Chandra Dey & Nakur Chandra Nandy',
        cuisine: 'Historic Bengali Sweets & Sandesh',
        location: '56 Ramdulal Sarkar Street, Hedua, Kolkata',
        distanceFromSite: '1.4 km from Kumartuli',
        priceForTwo: '₹120 - ₹300',
        rating: 4.9,
        signatureFoods: ['Jolbhora Sandesh (Liquid Saffron Jaggery Core)', 'Nolen Gur Soufflé Sandesh', 'Parijat', 'Kasturi Sandesh'],
        description: 'Founded in 1844, this sacred confectionery sweetshop is revered as Kolkata’s master artisan of hand-molded sandesh.',
        link: 'https://maps.google.com/?q=Nakur+Chandra+Nandy+Kolkata',
      },
    ],
  },
};

/**
 * Helper to fetch travel guide for any monument ID with fallback
 */
export function getNearbyGuideForSite(siteId: string): SiteTravelGuide {
  if (NEARBY_STAYS_FOOD_DATABASE[siteId]) {
    return NEARBY_STAYS_FOOD_DATABASE[siteId];
  }
  // Return Hawa Mahal as safe fallback
  return NEARBY_STAYS_FOOD_DATABASE['hawa-mahal'];
}
